---
title: "Neural Network"

date: "2023-05-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

suppressMessages(library(caret))
suppressMessages(library(tidyverse))
suppressMessages(library(randomForest))
suppressMessages(library(MLmetrics))
suppressMessages(library(neuralnet))

#Loading DataSet
data <- read.csv("API.csv")
data <- data %>% select(-date_time,-is_holiday)

#Encoding categotical to numerical
dummy_data <- dummyVars(" ~.", data=data)
data <- data.frame(predict(dummy_data, newdata=data))

#data Normalizing
preprocess_data <- preProcess(data, method=c("range"))
data_n <- predict(preprocess_data, data)
nrow(data_n)
#test-train Splitting
set.seed(333)
sample <- sample(c(TRUE, FALSE), nrow(data_n), replace=TRUE, prob=c(0.7,0.3))
data_train  <- data_n[sample,]
data_test   <- data_n[!sample,]

data_test_X <- data_test %>% select(-air_pollution_index)
data_test_Y <- data_test %>% select(air_pollution_index)

#Training Neural Network
names <- names(data_train)
f <- as.formula(paste("air_pollution_index ~", paste(names[!names %in% "air_pollution_index"], collapse = " + ")))
trainset = model.matrix(~., data=data_train)
fit_nn <- neuralnet(f,data=trainset[,-c(0:1)],hidden=c(8,4),linear.output=T, stepmax = 1e+05, rep = 1)

pred_nn <- predict(fit_nn, newdata = data_test_X)
View(data_test_Y)
View(pred_nn)

MSE_nn <- mean((data_test_Y$air_pollution_index - pred_nn)^2)
rmse_nn <- sqrt(MSE_nn)
rmse_nn


```
