---
title: "XGBOOST"
author: "Anushruti"
date: "2023-05-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(R6018)     # functions for SYS-6018
library(tidyverse) # functions for data manipulation  
library(randomForest)
library(caret)
library(xgboost)
suppressMessages(library(neuralnet))
```

```{r}
input.df <- read.csv("/Users/anushruti/Desktop/Data Mining/Project/API.csv")
view(input.df)
```

```{r}
#Data Preprocessing
input.df = subset(input.df, select = -c(date_time,is_holiday) )
df <- dummyVars(" ~ .", data=input.df)
processed.df <- data.frame(predict(df, newdata=input.df))

preprocess_data <- preProcess(processed.df, method=c("range"))
data_n <- predict(preprocess_data, processed.df)
```

```{r}
set.seed(333)
#pairs(input.df[,c("wind_direction","visibility_in_miles","dew_point","temperature","rain_p_h","snow_p_h","clouds_all","air_pollution_index","traffic_volume")])
sample <- sample(c(TRUE, FALSE), nrow(data_n), replace=TRUE, prob=c(0.7,0.3))

train  <- data_n[sample, ]
test <- data_n[!sample, ]

train_x = data.matrix(subset(train,select=(-c(air_pollution_index))))
train_y = data.matrix(train[,"air_pollution_index"])

test_x = data.matrix(subset(test,select=(-c(air_pollution_index))))
test_y = data.matrix(test[,"air_pollution_index"])

xgb_train = xgb.DMatrix(data = train_x, label = train_y)
xgb_test = xgb.DMatrix(data = test_x, label = test_y)


params <- list(booster = "gbtree", eta=0.3, gamma=0, max_depth=6, min_child_weight=1, subsample=1, colsample_bytree=1)


cv.res <- xgb.cv( params = params, data = xgb_train, nrounds = 10000, nfold = 10, showsd = T, stratified = T, print_every_n = 10, early_stopping_rounds = 20, maximize = F)
cv.res$best_iteration

model = xgboost(data = train_x, label = train_y, booster = "gbtree",max_depth = 6, eta = 0.3, nrounds = cv.res$best_iteration,objective="reg:squarederror",gamma=0,min_child_weight=1, subsample=1, colsample_bytree=1)
y_hat <- predict(model,newdata = test_x)
rmse <-sqrt(mean((test_y - y_hat)^2))
rmse
```

